export enum END_POINT {
    USER = '/user',
    SIGNUP = '/signup',
    LOGIN = '/login',
    PROFILE= '/profile',
    OTP='/otp',
    RESENDOTP='/resendotp',
    
    EMAIL='/email',
    EMAILOTP='/emailotp',
    EMAILOTPRESEND='/resendemailotp',

    UPGRADE='/upgrade',
    OTP2FA='/otp2fa',
    UPGRADEGREEN='/upgradegreen',
    UPGRADEBLUE='/upgradeblue',

    USERNAMECHECK='/usernamecheck',
    USERNAMEPURCHASE='/usernamepurchase',
    USERNAMESUGGESTION='/usernamesuggestion',
    UPDATETICKER='/updateticker',

    CREATEFEUD='/createfeud',
    MYFEUDS='/myfeud',
    NOTIFICATION='/notification',
    ACCEPTMODERATOR='/acceptmoderator',
    GETVOTECOUNT='/getvotecount',
    VOTECOUNT='/votecount',
    JOINFEUD='/joinfeud',
    EDITFEUD='/editfeud',
    CANCELFEUD='/cancelfeud',
    CANCELFEUDRESERVATION='/cancelfeudreservation',
    HOSTFEUD='/hostfeud',
    RENTBACKSKIN='/rentbackskin',
    ITEMVISIBILITY='/itemvisibility',
    JOINFEUDSDATA='/joinfeudsdata',
    KICKOUTMODERATORRULE='/kickoutmoderatorrule',
    KICKOUTCOUNT='/kickoutcount',
    KICKOUTVOTE='/kickoutvote',
    ENDFEUDRESPONSE='/endfeudresponse',
    FEUDLIKES='/feudlike',
    GETFEUDLIKES='/getfeudlike',
    FEUDSAVES='/feudsave',
    GETFEUDSAVES='/getfeudsave',
    STARTFEUD='/startfeud',
    LEAVEFEUD='/leavefeud',
    ENDFEUD='/endfeud'
  }